### ISSUE TITLE
Crash because of map access confliction

### ISSUE THREAD

**Issue by hajimehoshi** [200sc/sprite-demo#3]
The below is part of crash log:

```
[oak]-------- Adding demo
[oak]-------- No logs directory found. No logs will be written to file.
[config:143]  [{{assets/ audio/ images/ font/} { ERROR} {480 640} {none 12 72  white} 60 60 false English Oak Window}]

~~~~~~~~~~~~~~~
Oak Seed: 1500786939943910728

~~~~~~~~~~~~~~~
[load:92]  [open /Users/hajimehoshi/go/src/github.com/200sc/sprite-demo/assets/audio: no such file or directory]
[loading:28]  [open /Users/hajimehoshi/go/src/github.com/200sc/sprite-demo/assets/audio: no such file or directory]
fatal error: concurrent map read and map write

goroutine 18 [running]:
runtime.throw(0x41f67cb, 0x21)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420039b88 sp=0xc420039b68
runtime.mapaccess1_faststr(0x41b7660, 0xc420f20a80, 0x41f0050, 0x4, 0x3b)
        /usr/local/go/src/runtime/hashmap_fast.go:217 +0x4cf fp=0xc420039be8 sp=0xc420039b88
github.com/oakmound/oak/render.(*Compound).GetDims(0xc420e75900, 0x40683b072e348620, 0xc420e75900)
        /Users/hajimehoshi/go/src/github.com/oakmound/oak/render/compound.go:148 +0x4d fp=0xc420039c20 sp=0xc420039be8
github.com/oakmound/oak/render.(*RenderableHeap).draw(0xc4200dc400, 0x42ce080, 0xc42001f208, 0x0, 0x0, 0x280, 0x1e0)
        /Users/hajimehoshi/go/src/github.com/oakmound/oak/render/drawHeap.go:130 +0x311 fp=0xc420039ca0 sp=0xc420039c20
github.com/oakmound/oak/render.(*DrawStack).Draw(0xc4200dc3c0, 0x42ce080, 0xc42001f208, 0x0, 0x0, 0x280, 0x1e0)
        /Users/hajimehoshi/go/src/github.com/oakmound/oak/render/drawStack.go:55 +0x99 fp=0xc420039d00 sp=0xc420039ca0
github.com/oakmound/oak.drawLoop()
        /Users/hajimehoshi/go/src/github.com/oakmound/oak/drawLoop.go:78 +0xaac fp=0xc420039fe0 sp=0xc420039d00
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420039fe8 sp=0xc420039fe0
created by github.com/oakmound/oak.lifecycleLoop
        /Users/hajimehoshi/go/src/github.com/oakmound/oak/lifecycle.go:57 +0x59c

goroutine 1 [syscall, locked to thread]:
golang.org/x/exp/shiny/driver/gldriver._Cfunc_startDriver()
        golang.org/x/exp/shiny/driver/gldriver/_obj/_cgo_gotypes.go:305 +0x41
golang.org/x/exp/shiny/driver/gldriver.main(0x41fa3c0, 0xc420010980, 0xc420055e60)
        /Users/hajimehoshi/go/src/golang.org/x/exp/shiny/driver/gldriver/cocoa.go:107 +0x51
golang.org/x/exp/shiny/driver/gldriver.Main(0x41fa3c0)
        /Users/hajimehoshi/go/src/golang.org/x/exp/shiny/driver/gldriver/gldriver.go:26 +0x2f
golang.org/x/exp/shiny/driver.main(0x41fa3c0)
        /Users/hajimehoshi/go/src/golang.org/x/exp/shiny/driver/driver_darwin.go:15 +0x2b
golang.org/x/exp/shiny/driver.Main(0x41fa3c0)
        /Users/hajimehoshi/go/src/golang.org/x/exp/shiny/driver/driver.go:24 +0x2b
github.com/oakmound/oak.Init(0x41f002c, 0x4)
        /Users/hajimehoshi/go/src/github.com/oakmound/oak/init.go:122 +0x6af
main.main()
        /Users/hajimehoshi/go/src/github.com/200sc/sprite-demo/core.go:62 +0x1f6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
```

**Comment by 200sc** [comment]
Check the develop branch of oak

**Comment by 200sc** [comment]
I'll merge the change in to a release sometime today

**Comment by 200sc** [comment]
Alternatively the reverting method doesn't use compounds so this won't happen

**Comment by 200sc** [comment]
@hajimehoshi The PR was merged into master for this fix, if you haven't checked develop.

**Comment by hajimehoshi** [comment]
Yeah, it looks like it's working now. Thank you for fixing.
